### ISSUE TITLE
FYI: Graphite client

### ISSUE THREAD

**Issue by felixge** [coredump/hoardd#1]
Just saw your module on the Changelog and wanted to point you to https://github.com/felixge/node-graphite which we're using in production over at transloadit.com.

I thought you might like it as it will take care of re-establishing the connection in case of errors.

--fg

**Comment by coredump** [comment]
OHAI, I knew I remembered your username from somewhere, I use your mysql client on hoardd mysql script ;) I will probably use your connection lib too. It would be cool if it supported sending to carbon UDP port so it would be easier for me to implement it :)

**Comment by felixge** [comment]
>  It would be cool if it supported sending to carbon UDP port so it would be easier for me to implement it :)

Sure. I won't get to that right away, but I'll merge a patch if you get to it before I do!

**Comment by coredump** [comment]
So I commited a branch with node-graphite but then I noticed that this changes a core part of hoardd: metrics that failed to be sent are re-sent when the connection to the server is back. I am not sure I want to do that. Check this: 22282a558a28a382a5f6b2c0ef5d487bb29ce9c2

**Comment by coredump** [comment]
Also, don't know if this is a coffee-script behavior but the `err` return from the `write` callback is undefined in case of success, not null :)

**Comment by felixge** [comment]
> So I commited a branch with node-graphite but then I noticed that this changes a core part of hoardd: metrics that failed to be sent are re-sent when the connection to the server is back. I am not sure I want to do that. Check this: 22282a5

Not sure what you mean. My graphite client will _not_ try to re-send data if it failed the first time. It will however try to re-establish the connection whenever it drops / there are write errors.

> Also, don't know if this is a coffee-script behavior but the err return from the write callback is undefined in case of success, not null :)

Check for `if not err` or something. Yes, I should be providing `null` if there was no error, but I don't think me as well as many other module authors get this right every time ; ).

That being said, I'll take a patch that fixes that.
